version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:latest
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: karaxl28
      MYSQL_DATABASE: password_manager
      MYSQL_USER: leegisker
      MYSQL_PASSWORD: 28sylaxl
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network: 
    driver: bridge
